name: Lint HTML & CSS

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Installer Node.js
        uses: actions/setup-node@60f8a91b6c1c62c1b2b4a9bb44c6fa8b4c7a1d44
        with:
          node-version: '18'

      - run: npm install
      - run: chmod +x ./node_modules/.bin/htmlhint
      - run: npm run lint:html

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@3f3b4f5f25d2f8d6e6c09b4c1a47a9e42cbb6f6e
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_LAFLEUR_DEVOPS_1 }}